services:
  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    environment:
      - DB_PARAMS=dbname=weather user=postgres password=MJWhzCSaU host=db port=5432
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MJWhzCSaU
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
